name: eli_tattoo
description: "Eli Tattoo Studio App"
publish_to: 'none'
version: 1.6.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # ðŸ”¹ Firebase Services
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.4
  firebase_storage: ^11.7.4
  firebase_messaging: ^14.8.4
  firebase_analytics: ^10.8.4
  firebase_database: ^10.4.4
  google_sign_in: ^6.2.1

  # ðŸ”¹ UI Components
  cupertino_icons: ^1.0.6
  google_fonts: ^4.0.4
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.9
  shimmer: ^3.0.0
  lottie: ^2.7.0
  animate_do: ^3.1.2
  animations: ^2.0.8
  table_calendar: ^3.0.9
  fl_chart: ^0.66.2
  calendar_view: ^1.1.0
  emoji_picker_flutter: ^1.6.3
  swipeable_tile: ^2.0.0+3
  timeago: ^3.6.0

  # ðŸ”¹ State Management
  provider: ^6.1.1
  get: ^4.6.6

  # ðŸ”¹ Maps & Location
  google_maps_flutter: ^2.5.3
  location: ^5.0.3
  geolocator: ^10.1.0

  # ðŸ”¹ Utils
  intl: ^0.19.0
  url_launcher: ^6.2.4
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^8.0.0
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  permission_handler: ^11.2.0
  connectivity_plus: ^5.0.2
  package_info_plus: ^4.0.0
  uuid: ^4.2.2

  # ðŸ”¹ QR & Barcode
  qr_flutter: ^4.1.0
  # â— Temporar comentat â€“ provoacÄƒ conflict pe iOS
  # mobile_scanner: ^3.0.0

  # ðŸ”¹ Multimedia
  photo_view: ^0.14.0
  giphy_picker: ^3.0.1
  video_player: ^2.8.2

  # ðŸ”¹ NotificÄƒri locale
  flutter_local_notifications: 14.1.1

  # ðŸ”¹ UI Enhancements
  glassmorphism_ui: ^0.3.0
  glassmorphism: ^3.0.0
  flutter_launcher_icons: ^0.13.1

  # ðŸ”¹ ðŸ” Chei API (.env)
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_native_splash: ^2.3.10

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/images/logo.png"

flutter_native_splash:
  color: "#000000"
  image: assets/images/logo.png
  android_12:
    image: assets/images/logo.png
    icon_background_color: "#000000"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/buttons/
    - assets/images/logo.png
    - assets/images/tbi_banner.png
    - assets/images/alecs_avatar.jpg
    - assets/images/blanca_avatar.jpg
    - assets/images/denis_avatar.jpg
    - .env

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Light.ttf
